name=AFS01Sensor
version=1.0.1
author=Jonathan Harrocks<lildev1979@outloook.com>
maintainer=Jonathan Harrocks<lildev1979@outloook.com>
sentence=An Arduino library for the AFS01 Gas Micro Flow Sensor over I2C.
paragraph=Implements raw data collection, processes signed measurements, and performs factory-compliant CRC8 data verification to handle bidirectional micro-flow gas sensing safely.
category=Sensors
url=https://github.com/lildev1979/AFS01Sensor
architectures=*